actors:
  iwashi:
    image_url: /images/actors/iwashi.jpeg
    name: iwashi
    url: https://twitter.com/iwashi86
  kaname:
    image_url: /images/actors/kaname.jpg
    name: __kaname__
    url: https://twitter.com/__kaname__
  kakakakakku:
    image_url: /images/actors/kakakakakku.png
    name: kakakakakku
    url: https://twitter.com/kakakakakku
  nitky:
    image_url: /images/actors/nitky.jpg
    name: nitky
    url: https://github.com/nitky
  slankdev:
    image_url: /images/actors/slankdev.jpg
    name: slankdev
    url: https://github.com/slankdev
  ykmc09:
    image_url: /images/actors/yokomichi.jpg
    name: ykmc09
    url: https://github.com/ykmc09
  TAKAKING22:
    image_url: /images/actors/TAKAKING22.jpeg
    name: TAKAKING22
    url: https://github.com/TAKAKING22
  kimhirokuni:
    image_url: /images/actors/kim.jpeg
    name: kimhirokuni 
    url: https://twitter.com/kimhirokuni
  kumagi:
    image_url: /images/actors/kumagi.jpg
    name: kumagi
    url: https://twitter.com/kumagi
  mamohacy:
    image_url: /images/actors/mamohacy.jpg
    name: mamohacy
    url: https://twitter.com/mamohacy
  rotsuya:
    image_url: /images/actors/rotsuya.jpg
    name: rotsuya
    url: https://twitter.com/rotsuya
  rafiror:
    image_url: /images/actors/rafiror.jpeg
    name: rafiror
    url: https://twitter.com/rafiror
  ryuzee:
    image_url: /images/actors/ryuzee.jpg
    name: ryuzee
    url: https://twitter.com/ryuzee
  twada:
    image_url: /images/actors/twada.png
    name: twada
    url: https://twitter.com/t_wada
  hiranabe:
    image_url: /images/actors/hiranabe.png
    name: hiranabe
    url: https://twitter.com/hiranabe
  320KZCD:
    image_url: /images/actors/320KZCD.jpg
    name: 320KZCD
    url: https://twitter.com/320KZCD
  yuyarin:
    image_url: /images/actors/yuyarin.jpg
    name: yuyarin
    url: https://twitter.com/yuyarin
  shinji_abe:
    image_url: /images/actors/shinji_abe.jpg
    name: shinji_abe
    url: https://twitter.com/shinji_abe
  takoratta:
    image_url: /images/actors/takoratta.jpg
    name: takoratta
    url: https://twitter.com/takoratta
  sorano_tarou:
    image_url: /images/actors/sorano_tarou.jpeg
    name: sorano_tarou 
    url: https://twitter.com/sorano_tarou
  hiroki_daichi:
    image_url: /images/actors/hiroki_daichi.jpg
    name: hiroki_daichi
    url: https://twitter.com/hiroki_daichi
  makoga:
    image_url: /images/actors/makoga.jpg
    name: makoga
    url: https://twitter.com/makoga
  yosuke_furukawa:
    image_url: /images/actors/yosuke_furukawa.jpg
    name: yosuke_furukawa
    url: https://twitter.com/yosuke_furukawa
  teppeis:
    image_url: /images/actors/teppeis.png
    name: teppeis
    url: https://twitter.com/teppeis
  noralife:
    image_url: /images/actors/noralife.png
    name: noralife
    url: https://twitter.com/noralife
  k_mrgk:
    image_url: /images/actors/k_mrgk.jpg
    name: k_mrgk
    url: https://twitter.com/k_mrgk
  toby:
    image_url: /images/actors/toby.png
    name: toby
    url: https://twitter.com/yosiaki6
  hiromisugie:
    image_url: /images/actors/hiromisugie.jpg
    name: hiromisugie
    url: https://twitter.com/hiromisugie
  tomoaki_mura:
    image_url: /images/actors/tomoaki_mura.jpg
    name: tomoaki_mura 
    url: https://twitter.com/tomoaki_mura
  tzkb:
    image_url: /images/actors/tzkb.png
    name: tzkb 
    url: https://twitter.com/tzkb
  songmu:
    image_url: /images/actors/songmu.jpg
    name: songmu
    url: https://twitter.com/songmu
  kenta_sato3:
    image_url: /images/actors/kenta_sato3.jpg
    name: kenta_sato3 
    url: https://twitter.com/kenta_sato3
  yunon_phys:
    image_url: /images/actors/yunon_phys.jpg
    name: yunon_phys
    url: https://twitter.com/yunon_phys
  lightling:
    image_url: /images/actors/lightling.jpg
    name: Lisette Sutherland
    url: https://twitter.com/lightling
  kawasy:
    image_url: /images/actors/kawasy.jpg
    name: kawasy
    url: https://twitter.com/kawasy
  konifar:
    image_url: /images/actors/konifar.jpg
    name: konifar
    url: https://twitter.com/konifar
  yuki_wtz:
    image_url: /images/actors/yuki_wtz.jpeg
    name: yuki_wtz 
    url: https://twitter.com/yuki_wtz
  raykataoka:
    image_url: /images/actors/raykataoka.jpg
    name: raykataoka
    url: https://twitter.com/raykataoka
  yohhatu:
    image_url: /images/actors/yohhatu.jpg
    name: yohhatu
    url: https://twitter.com/yohhatu
  JunMakishi:
    image_url: /images/actors/JunMakishi.jpg
    name: JunMakishi
    url: https://twitter.com/JunMakishi
  tomomiminabe:
    image_url: /images/actors/tomomiminabe.jpeg
    name: tomomiminabe
    url: https://twitter.com/tomomiminabe
  941:
    image_url: /images/actors/941.jpg
    name: 941
    url: https://twitter.com/941
  nakabonne:
    image_url: /images/actors/nakabonne.jpeg
    name: nakabonne
    url: https://twitter.com/nakabonne
  TokunagaKohei:
    image_url: /images/actors/tokunagaKohei.jpg
    name: Kohei Tokunaga
    url: https://twitter.com/TokunagaKohei
  TakahiroOmi:
    image_url: /images/actors/TakahiroOmi.jpeg
    name: Takahiro Omi
    url: https://sites.google.com/view/omitakahiro/
  yasudatadahiro:
    image_url: /images/actors/yasuda.jpeg
    name: yasudatadahiro
    url: https://twitter.com/yasudatadahiro
  Nunerm:
    image_url: /images/actors/Nunerm.png
    name: Nunerm
    url: https://twitter.com/Nunerm
  yamamuteking:
    image_url: /images/actors/yamamuteking.jpeg
    name: yamamuteking
    url: https://twitter.com/yamamuteking
  7omich:
    image_url: /images/actors/7omich.jpeg
    name: 7omich
    url: https://twitter.com/7omich
  t-kurimura:
    image_url: /images/actors/t-kurimura.jpeg
    name: t-kurimura
    url: https://twitter.com/t_kurimura
  nakakura:
    image_url: /images/actors/nakakura.jpeg
    name: nakakura
    url: https://github.com/nakakura
  kmat:
    image_url: /images/actors/kmat.jpeg
    name: kmat
    url: https://github.com/Hakomatsu
  YukiAnzai:
    image_url: /images/actors/YukiAnzai.jpeg
    name: YukiAnzai
    url: https://twitter.com/YukiAnzai
  ffu_:
    image_url: /images/actors/ffu_.jpeg
    name: ffu_
    url: https://twitter.com/ffu_
  miholovesq:
    image_url: /images/actors/miholovesq.jpeg
    name: miholovesq
    url: https://twitter.com/miholovesq
  sakata_akinori:
    image_url: /images/actors/sakata_akinori.jpeg
    name: sakata_akinori
    url: https://twitter.com/sakata_akinori
  tsukkee:
    image_url: /images/actors/tsukkee.jpeg
    name: tsukkee
    url: https://twitter.com/tsukkee
  kameike:
    image_url: /images/actors/kameike.jpeg
    name: kameike
    url: https://twitter.com/kameike
  AIcia_Solid:
    image_url: /images/actors/aicia_solid.jpeg
    name: AIcia_Solid
    url: https://twitter.com/AIcia_Solid
  morishin127:
    image_url: /images/actors/morishin.jpeg
    name: morishin127
    url: https://twitter.com/morishin127
  motoi:
    image_url: /images/actors/motoi.jpeg
    name: motoi
    url: https://twitter.com/motoi
  kedamatti:
    image_url: /images/actors/kedamatti.jpeg
    name: kedamatti
    url: https://twitter.com/kedamatti
  g_suzutatsu:
    image_url: /images/actors/g_suzutatsu.jpeg
    name: g_suzutatsu
    url: https://twitter.com/g_suzutatsu
  r1ccha:
    image_url: /images/actors/r1ccha.jpeg
    name: r1ccha
    url: https://twitter.com/r1ccha
  mmasaki:
    image_url: /images/actors/mmasaki.jpeg
    name: mmasaki 
    url: https://github.com/mmasaki
  Keisuke69:
    image_url: /images/actors/Keisuke69.jpeg
    name: Keisuke69
    url: https://twitter.com/Keisuke69
  hsbt:
    image_url: /images/actors/hsbt.png
    name: hsbt
    url: https://twitter.com/hsbt
  watal_i27e:
    image_url: /images/actors/watal_i27e.jpeg
    name: watal_i27e
    url: https://twitter.com/watal_i27e
  tkEzaki:
    image_url: /images/actors/tkEzaki.jpeg
    name: tkEzaki
    url: https://twitter.com/tkEzaki
  bto:
    image_url: /images/actors/bto.jpeg
    name: BTO
    url: https://twitter.com/bto
  zsc:
    image_url: /images/actors/zsc.png
    name: Zachary Sarah Corleissen
    url: https://corleissen.com/
  oguma:
    image_url: /images/actors/oguma.jpeg
    name: Takashi Oguma
    url: https://www.facebook.com/bear.mini
  vaaaaanquish:
    image_url: /images/actors/vaaaaanquish.jpeg
    name: vaaaaanquish
    url: https://twitter.com/vaaaaanquish
  l2k:
    image_url: /images/actors/l2k.jpeg
    name: Lukas Biewald
    url: https://twitter.com/l2k
  hamaken119:
    image_url: /images/actors/hamaken119.jpeg
    name: hamaken119
    url: https://twitter.com/hamaken119
  ryohtaka:
    image_url: /images/actors/ryohtaka.jpg
    name: ryohtaka
    url: https://twitter.com/ryohtaka117
  tomiyama:
    image_url: /images/actors/tomiyama.jpeg
    name: tomiyama
    url: https://www.facebook.com/masaaki.tomiyama.7
  g1m1et0212:
    image_url: /images/actors/succhiello.jpeg
    name: g1m1et0212
    url: https://twitter.com/g1m1et0212
  jacopen:
    image_url: /images/actors/jacopen.jpeg
    name: jacopen
    url: https://twitter.com/jacopen
  ykajiaaaaa:
    image_url: /images/actors/ykajiaaaaa.jpeg
    name: y.kajiura
    url: https://twitter.com/ykajiaaaaa
  sandayuu:
    image_url: /images/actors/sandayuu.jpeg
    name: sandayuu
    url: https://twitter.com/sandayuu
  yutadayo:
    image_url: /images/actors/yutadayo.jpeg
    name: yutadayo
    url: https://twitter.com/yutadayo
  yoichiro:
    image_url: /images/actors/yoichiro.jpeg
    name: yoichiro
    url: https://twitter.com/yoichiro
  udzura:
    image_url: /images/actors/udzura.jpeg
    name: Uchio Kondo
    url: https://twitter.com/udzura
  tai:
    image_url: /images/actors/tai.jpeg
    name: Nobuhiro Tai
    url: https://www.linkedin.com/in/%E5%AE%A3%E8%A3%95-%E7%94%B0%E4%BA%95-371498279
  dmytro:
    image_url: /images/actors/dmytro.webp
    name: Dmytro Yarmak
    url: https://www.linkedin.com/in/dmytro-yarmak/
  spring_aki:
    image_url: /images/actors/spring_aki.jpeg
    name: Aki
    url: https://x.com/spring_aki
  chikathreesix:
    image_url: /images/actors/chikathreesix.jpg
    name: Ryo Chikazawa
    url: https://x.com/chikathreesix
  piqcy:
    image_url: /images/actors/piqcy.jpg
    name: Takahiro Kubo
    url: https://x.com/icoxfog417
  kosukearima:
    image_url: /images/actors/kosukearima.jpg
    name: Kosuke Arima
    url: https://x.com/kosukearima
  miwa_ensan:
    image_url: /images/actors/miwa_ensan.jpg
    name: miwa_ensan
    url: https://x.com/miwa_ensan
  noriyuki_kojima:
    image_url: /images/actors/noriyuki_kojima.jpg
    name: Noriyuki Kojima
    url: https://x.com/noriyuki_kojima
  dora_e_m:
    image_url: /images/actors/dora_e_m.jpg
    name: 190ODA（いくお）
    url: https://x.com/dora_e_m
  danno:
    image_url: /images/actors/danno.jpg
    name: 檀野 隆一
    url: #
  markunet:
    image_url: /images/actors/markunet.jpg
    name: Masayuki Kobayashi
    url: https://x.com/markunet
  aztecher_:
    image_url: /images/actors/aztecher_.jpg
    name: Mikiya Michishita
    url: https://x.com/aztecher_
  toru_kita:
    image_url: /images/actors/toru_kita.jpg
    name: Toru Kitagawa
    url: https://x.com/toru_kita
  agektmr:
    image_url: /images/actors/agektmr.jpg
    name: えーじ
    url: https://x.com/agektmr
  kumassy_:
    image_url: /images/actors/kumassy_.jpg
    name: くまっしー
    url: https://x.com/kumassy_
  kamiyaU:
    image_url: /images/actors/kamiyaU.jpg
    name: kamiyaU
    url: https://x.com/_yukamiya
  hudebakonosoto:
    image_url: /images/actors/hudebakonosoto.jpg
    name: hudebakonosoto
    url: https://x.com/hudebakonosoto
  nekokak:
    image_url: /images/actors/nekokak.jpeg
    name: nekokak
    url: https://x.com/nekokak
  yasukawa0713:
    image_url: /images/actors/yasukawa0713.jpg
    name: yasukawa0713
    url: https://x.com/yasukawa0713
  LoveIdahoBurger:
    image_url: /images/actors/LoveIdahoBurger.jpg
    name: Aki
    url: https://x.com/LoveIdahoBurger
author: iwashi
description: 技術・組織・マネジメントなどを深掘りして楽しむPodcastです。 #fukabori
description_long: 何らかの技術・組織・マネジメントなどに詳しいゲストを読んで、その入門から応用的な内容まで深掘りしていくPodcast
email: fukabori.fm@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-50413464-3
hashtag: fukabori
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/fukabori-fm/id1388826609
keywords: fukabori,podcast,技術
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: fukabori.fm
url: https://fukabori.fm
